chore: refactor pipelines, update deps

diff --git a/.github/workflows/push_to_develop.yml b/.github/workflows/push_to_develop.yml
--- a/.github/workflows/push_to_develop.yml
+++ b/.github/workflows/push_to_develop.yml
@@ -14,8 +14,96 @@ env:
   FOUNDRY_PROFILE: ci
 
 jobs:
+  format:
+    name: Check formatting
+    runs-on: general
+    container:
+      image: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/node-extended:9cc81226
+      credentials:
+        username: _json_key_base64
+        password: ${{ secrets.GCP_DOCKER_IMAGES_REGISTRY_SERVICE_ACCOUNT }}
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Init env
+        run: yarn install
+
+      - name: Check formatting
+        run: yarn format:check
+
+  lint:
+    name: Run linter
+    runs-on: general
+    container:
+      image: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/node-extended:9cc81226
+      credentials:
+        username: _json_key_base64
+        password: ${{ secrets.GCP_DOCKER_IMAGES_REGISTRY_SERVICE_ACCOUNT }}
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Init env
+        run: yarn install
+
+      - name: Linter
+        run: yarn lint
+
+  lint-commits:
+    name: Lint commits
+    runs-on: general
+    container:
+      image: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/node-extended:9cc81226
+      credentials:
+        username: _json_key_base64
+        password: ${{ secrets.GCP_DOCKER_IMAGES_REGISTRY_SERVICE_ACCOUNT }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Init env
+        run: yarn install
+
+      - name: Lint commits
+        run: yarn lint:commits
+
+  analyze:
+    name: Analyze with Slither
+    runs-on: general
+    container:
+      image: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/node-extended:9cc81226
+      credentials:
+        username: _json_key_base64
+        password: ${{ secrets.GCP_DOCKER_IMAGES_REGISTRY_SERVICE_ACCOUNT }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Init env
+        run: yarn install
+
+      - name: Run Slither
+        shell: "bash {0}"
+        run: |
+          yarn slither:ci
+          exit_code=$?
+          echo '```' > $GITHUB_STEP_SUMMARY
+          cat reports/slither.txt >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          exit $exit_code
+
   build-image:
     name: Build Docker Image
+    needs:
+      - format
+      - lint
+      - lint-commits
+      - analyze
     runs-on:
       - general
     steps:
@@ -58,34 +146,6 @@ jobs:
           cache-from: type=registry,ref=${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/core:buildcache
           cache-to: type=registry,ref=${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/core:buildcache,mode=max
 
-
-  format:
-    name: Check formatting
-    needs: build-image
-    runs-on: general
-    container:
-      image: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/core:${{ github.sha }}
-      credentials:
-        username: _json_key_base64
-        password: ${{ secrets.GCP_DOCKER_IMAGES_REGISTRY_SERVICE_ACCOUNT }}
-
-    steps:
-      - name: Check formatting
-        run: "cd /app; yarn format:check"
-
-  lint:
-    name: Run linter
-    needs: build-image
-    runs-on: general
-    container:
-      image: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/core:${{ github.sha }}
-      credentials:
-        username: _json_key_base64
-        password: ${{ secrets.GCP_DOCKER_IMAGES_REGISTRY_SERVICE_ACCOUNT }}
-
-    steps:
-      - name: Linter
-        run: "cd /app; yarn lint"
 
   # Technically we don't need to build step is done during the docker build
   build:
@@ -142,88 +202,63 @@ jobs:
           path: '*.xml'                     # Path to test results (inside artifact .zip)
           reporter: java-junit              # Format of test results
 
-  #  # Coverage fails on 'Yul exception:Variable expr is 1 too deep in the stack'
-  #  coverage:
-  #    runs-on: general
-  #    permissions:
-  #      contents: read
-  #      pull-requests: write
-  #
-  #    steps:
-  #      - uses: actions/checkout@v4
-  #        with:
-  #          submodules: recursive
-  #
-  #      - name: Setup node
-  #        uses: actions/setup-node@v4
-  #        with:
-  #          node-version-file: 'package.json'
-  #
-  #      - name: Install Foundry
-  #        uses: onbjerg/foundry-toolchain@v1
-  #
-  #      - name: Install dependencies
-  #        run: "corepack enable && yarn install"
-  #
-  #      - name: Run Forge build
-  #        run: "forge --version && yarn build --sizes"
-  #
-  #      - name: Run forge coverage
-  #        id: coverage
-  #        env:
-  #          TEST_RPC_URL: "https://eth.llamarpc.com"
-  #          TEST_SAFE_SINGLETON: "0x41675C099F32341bf84BFc5382aF534df5C7461a"
-  #          TEST_SAFE_PROXY_FACTORY: "0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67"
-  #        run: |
-  #          {
-  #          echo 'COVERAGE<<EOF'
-  #          forge coverage --ir-minimum --summary | awk '/Test Summary:/{y=1;next}y'
-  #          echo EOF
-  #          } >> "$GITHUB_OUTPUT"
-  #
-  #      - name: Comment on PR
-  #        id: comment
-  #        uses: actions/github-script@v7
-  #        with:
-  #          github-token: ${{ secrets.TOKEN_GITHUB }}
-  #          script: |
-  #            const output = `${{ steps.coverage.outputs.COVERAGE }}`;
-  #            const commentBody = `Forge code coverage:\n${output}\n`;
-  #            github.rest.issues.createComment({
-  #              issue_number: context.issue.number,
-  #              owner: context.repo.owner,
-  #              repo: context.repo.repo,
-  #              body: commentBody
-  #            });
-
-  #  # Blocked by OSU-502
-  #  analyze:
-  #    name: Analyze with Slither
-  #    runs-on: general
-  #    steps:
-  #      - uses: actions/checkout@v4
-  #        with:
-  #          submodules: recursive
-  #
-  #      - name: Setup node
-  #        uses: actions/setup-node@v4
-  #        with:
-  #          node-version-file: 'package.json'
-  #
-  #      - name: Install Foundry
-  #        uses: onbjerg/foundry-toolchain@v1
-  #
-  #      - name: Install dependencies
-  #        run: "corepack enable && yarn install"
-  #
-  #      - name: Run Slither
-  #        run: "yarn slither:setup && yarn slither"
+#  # Coverage fails on 'Yul exception:Variable expr is 1 too deep in the stack'
+#  coverage:
+#    runs-on: general
+#    permissions:
+#      contents: read
+#      pull-requests: write
+#
+#    steps:
+#      - uses: actions/checkout@v4
+#        with:
+#          submodules: recursive
+#
+#      - name: Setup node
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version-file: 'package.json'
+#
+#      - name: Install Foundry
+#        uses: onbjerg/foundry-toolchain@v1
+#
+#      - name: Install dependencies
+#        run: "corepack enable && yarn install"
+#
+#      - name: Run Forge build
+#        run: "forge --version && yarn build --sizes"
+#
+#      - name: Run forge coverage
+#        id: coverage
+#        env:
+#          TEST_RPC_URL: "https://eth.llamarpc.com"
+#          TEST_SAFE_SINGLETON: "0x41675C099F32341bf84BFc5382aF534df5C7461a"
+#          TEST_SAFE_PROXY_FACTORY: "0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67"
+#        run: |
+#          {
+#          echo 'COVERAGE<<EOF'
+#          forge coverage --ir-minimum --summary | awk '/Test Summary:/{y=1;next}y'
+#          echo EOF
+#          } >> "$GITHUB_OUTPUT"
+#
+#      - name: Comment on PR
+#        id: comment
+#        uses: actions/github-script@v7
+#        with:
+#          github-token: ${{ secrets.TOKEN_GITHUB }}
+#          script: |
+#            const output = `${{ steps.coverage.outputs.COVERAGE }}`;
+#            const commentBody = `Forge code coverage:\n${output}\n`;
+#            github.rest.issues.createComment({
+#              issue_number: context.issue.number,
+#              owner: context.repo.owner,
+#              repo: context.repo.repo,
+#              body: commentBody
+#            });
 
   deploy-contract:
     name: Deploy contracts
     needs:
-      - lint
-      - format
       - build
       - test
     runs-on: general
@@ -263,22 +298,28 @@ jobs:
   publish:
     name: Publish
     needs:
-      - build-image
-      - format
-      - lint
+      - build
       - test
     runs-on: general
     container:
-      image: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/ci/core:${{ github.sha }}
+      image: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/node-extended:9cc81226
       credentials:
         username: _json_key_base64
         password: ${{ secrets.GCP_DOCKER_IMAGES_REGISTRY_SERVICE_ACCOUNT }}
     steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Init env
+        run: yarn install
+
       - name: Build
-        run: "cd /app; yarn build:contracts"
+        run: yarn build:contracts
 
       - name: Set npm auth token
-        run: "cd /app; yarn config set npmScopes.golemfoundation.npmAuthToken ${{ secrets.HOUSEKEEPER_PAT_OCTANT_V2_PACKAGES }}"
+        run: yarn config set npmScopes.golemfoundation.npmAuthToken ${{ secrets.HOUSEKEEPER_PAT_OCTANT_V2_PACKAGES }}
 
       - name: Publish
-        run: "cd /app; yarn release --preRelease"
+        run: yarn release --preRelease
